compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules
npmScopes:
  fortawesome:
    npmRegistryServer: https://npm.fontawesome.com/
    npmAuthToken: "19D5D70D-2FDB-4692-A632-DEED300EA88C"
